sonar.organization=nicosingh-1
sonar.projectKey=f76b4bd294b4971a207e4bb746ccbc873148041c

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=src