name: Java CI with Maven

on:
  push

env:
  JAVA_VERSION: '17'

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/actions/maven
        with:
          maven-task: build
          java-version: '17'
        
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: ./.github/actions/maven
        with:
          maven-task: test
          java-version: '17'