---
name: Java CI with Maven

on:
  push

env:
  JAVA_VERSION: '17'

jobs:
  alpine:
    name: Docker Container Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-container

  lint:
    name: Lint Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: ./.github/actions/yamllint
        with:
          scan-path: '.'

  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/maven
        with:
          maven-task: package

  test:
    name: Test Job
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/maven
        with:
          maven-task: test
          java-version: ${{ env.JAVA_VERSION }}

  another-test:
    name: Another Test Job
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/maven
        with:
          maven-task: test
          java-version: ${{ env.JAVA_VERSION }}
