name: Java CI with Maven

on:
  push

env:
  JAVA_VERSION: '17'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: cytopia/yamllint
      volumes:
        - ${{github.workspace}}:/data
    steps:
      - run: ls -lrtha /data
      - run: hostname
      - run: yamllint .

  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/maven
        with:
          maven-task: package

  test:
    name: Test Job
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/maven
        with:
          maven-task: test
          java-version: ${{ env.JAVA_VERSION }}
  
  another-test:
    name: Another Test Job
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/maven
        with:
          maven-task: test
          java-version: ${{ env.JAVA_VERSION }}